//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRClientTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISSATGE
    {
        public int NUM_MIS { get; set; }
        public string CODI_VHI { get; set; }
        public string TIPUS_MIS { get; set; }
        public string ACCIO_MIS { get; set; }
        public Nullable<System.DateTime> DATA_MIS { get; set; }
        public string NUM_SRV { get; set; }
        public Nullable<System.DateTime> DATA_LLOC { get; set; }
        public string DIR_INICI { get; set; }
        public string DIR_FINAL { get; set; }
        public string POB_INICI { get; set; }
        public string POB_FINAL { get; set; }
        public string PRV_INICI { get; set; }
        public string PRV_FINAL { get; set; }
        public Nullable<decimal> EDAT { get; set; }
        public string CODI_PAC { get; set; }
        public string NOM { get; set; }
        public string COGNOMS { get; set; }
        public string CODI_XOF { get; set; }
        public string CODI_MET { get; set; }
        public string CODI_ENF { get; set; }
        public string CODI_TRM { get; set; }
        public string CODI_TRA { get; set; }
        public string CODI_SIN { get; set; }
        public string CODI_DIG { get; set; }
        public string TIPUS_SRV { get; set; }
        public Nullable<double> LITRES { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<double> IMPORT { get; set; }
        public string REFERENCIA { get; set; }
        public string TEL_SRV { get; set; }
        public string TIPUS_TARGETA { get; set; }
        public string DADES_TARGETA { get; set; }
        public Nullable<short> ACOMPANYANT { get; set; }
        public Nullable<short> P10 { get; set; }
        public string CIP { get; set; }
        public string NASS { get; set; }
        public string DNI { get; set; }
        public string CODI_CLA { get; set; }
        public string CODI_ANU { get; set; }
        public string CODI_LOT { get; set; }
        public string CONFLICTIVITAT { get; set; }
        public string PRIORITAT { get; set; }
        public string OBS { get; set; }
        public Nullable<int> ESTAT { get; set; }
        public Nullable<System.DateTime> DATA_INICI_SRV { get; set; }
        public string CODI_AJU { get; set; }
        public string CODI_EMP { get; set; }
        public Nullable<double> X_1 { get; set; }
        public Nullable<double> Y_1 { get; set; }
        public Nullable<double> X_2 { get; set; }
        public Nullable<double> Y_2 { get; set; }
        public string DES_RUTA { get; set; }
        public string RUTA { get; set; }
        public Nullable<int> NUM_SRV_RUTA { get; set; }
        public Nullable<int> NUM_SRV_TOTAL_RUTA { get; set; }
        public string ACCIO_RUTA { get; set; }
        public Nullable<decimal> NUM_ENVIAMENT { get; set; }
        public Nullable<short> OXIGEN { get; set; }
        public Nullable<decimal> MENSAJE_TX { get; set; }
        public Nullable<int> REINTENTOS { get; set; }
        public Nullable<decimal> HOME_SI_NO { get; set; }
        public Nullable<System.DateTime> DATA_NEIX { get; set; }
        public Nullable<System.DateTime> DATA_ENVIA { get; set; }
        public string CODI_CHK { get; set; }
        public string SYS_215_CHK { get; set; }
        public string TEST_1 { get; set; }
        public Nullable<decimal> UNITATS_DEMANADES { get; set; }
        public string TEST_2 { get; set; }
    }
}
